name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image_name: brezyweather
      tag: 1.0.0

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log into the ACR
      run: docker login $ACR_SERVER --username "$ACR_USERNAME" --password "$ACR_PASSWORD"
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Push the docker image
      run: |
        docker tag $image_name $ACR_SERVER/$image_name:$tag
        docker push $ACR_SERVER/$image_name:$tag
        
